services:
  user_db:
    container_name: user_db
    image: postgres:15
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - '5440:5432'
    networks:
      - marketplace-network

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://user_db/user_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: user
    ports:
      - '8090:8080'
    command:
      - start-dev
    depends_on:
      - user_db
    networks:
      - marketplace-network

volumes:
  user_db:

networks:
  marketplace-network:
    driver: bridge
